name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --cfg portable_io_unstable_all

jobs:
  # General TODO items:
  # - try Rust clippy (should avoid all warnings)
  # - check for build & test warnings
  # - enforce consistent Rust fmt (if possible without affecting too much code)
  test:
    strategy:
      matrix:
        include:
          - rust: nightly
          - os: macos-latest
            rust: nightly
          - os: windows-latest
            rust: nightly
          - rust: nightly-2024-07-01
          - rust: nightly-2023-07-01
            test-options: --all-targets # SKIP doc tests
          - rust: nightly-2022-08-24 # MSRV (nightly)
            test-options: --all-targets # SKIP doc tests
          # TEST with these Rust nightly versions to check for correct rustversion conditions in `src/readbuf.rs`
          - rust: nightly-2024-02-17
            test-options: --all-targets # SKIP doc tests
          - rust: nightly-2024-02-16
            test-options: --all-targets # SKIP doc tests
          - rust: nightly-2024-02-15
            test-options: --all-targets # SKIP doc tests
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup default ${{ matrix.rust }}
      # TODO: MOVE CARGO BUILD TEST TO NEW BUILD JOB & CHECK FOR ANY BUILD WARNINGS TO BE RESOLVED
      - run: cargo build --no-default-features --verbose
      # XXX TBD SKIP DOC TESTS WITH NO FEATURES FOR NOW - XXX TBD ??? ???
      - run: cargo test --no-default-features --all-targets --verbose
      # TODO: MOVE CARGO BUILD TEST TO NEW BUILD JOB & CHECK FOR ANY BUILD WARNINGS TO BE RESOLVED
      # (NO NEED FOR EXTRA TEST OPTIONS IN CARGO BUILD STEP HERE)
      - run: cargo build --features alloc ${{ matrix.test-options }} --verbose
      - run: cargo test --features alloc ${{ matrix.test-options }} --verbose
      # XXX TODO BUILD & UNIT TESTING WITH FEATURE: readbuf
      # TODO: MOVE CARGO BUILD TEST TO NEW BUILD JOB & CHECK FOR ANY BUILD WARNINGS TO BE RESOLVED
      # (NO NEED FOR EXTRA TEST OPTIONS IN CARGO BUILD STEP HERE)
      - run: cargo build --all-features ${{ matrix.test-options }} --verbose
        if: (!startsWith(matrix.os, 'windows'))
      - run: cargo test --all-features ${{ matrix.test-options }} --verbose
        if: (!startsWith(matrix.os, 'windows'))

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup default nightly
      - run: cargo doc --all-features
