name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --cfg portable_io_unstable_all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup default nightly
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: cargo test --all-features --verbose
    # TODO: IMPROVE CONSISTENCY WITH STEPS ABOVE
    - run: cargo doc --all-features
    # TEST with Rust nightly back to July 2024 - TODO USE MATRIX FOR THIS
    - run: rustup default nightly-2024-07-01
    - run: cargo test --all-features
