name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --cfg portable_io_unstable_all

jobs:
  # General TODO items:
  # - try Rust clippy (should avoid all warnings)
  # - check for build & test warnings
  # - enforce consistent Rust fmt (if possible without affecting too much code)
  build:
    runs-on: ubuntu-latest
    # TODO: IMPROVE CONSISTENCY OF INDENTING WITH INDENTING OF push branches above
    steps:
    - uses: actions/checkout@v4
    - run: rustup default nightly
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: cargo test --all-features --verbose
    # TODO: IMPROVE CONSISTENCY WITH STEPS ABOVE
    - run: cargo doc --all-features
    # TODO: USE MATRIX FOR TESTING WITH OTHER RUST NIGHTLY VERSIONS
    - run: git clean -dfX # QUICK WORKAROUND to remove Cargo lock file version 4
    # (NEED TO USE `--all-targets` to avoid issues with doc tests on some older Rust nightly versions below)
    # TEST with MSRV (nightly)
    - run: rustup default nightly-2022-08-24
    - run: cargo test --all-features --all-targets
    # TEST with Rust nightly from mid-2023
    - run: rustup default nightly-2023-07-01
    - run: cargo test --all-features --all-targets
    # TEST with Rust nightly from late-February 2024 to check for correct rustversion conditions
    - run: rustup default nightly-2024-02-17
    - run: cargo test --all-features --all-targets
    - run: rustup default nightly-2024-02-16
    - run: cargo test --all-features --all-targets
    - run: rustup default nightly-2024-02-15
    - run: cargo test --all-features --all-targets
    # TEST with a more recent Rust nightly version (no need for --all-targets)
    - run: rustup default nightly-2024-07-01
    - run: cargo test --all-features
