name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --cfg portable_io_unstable_all

jobs:
  # General TODO items:
  # - try Rust clippy (should avoid all warnings)
  # - check for build & test warnings
  # - enforce consistent Rust fmt (if possible without affecting too much code)
  build:
    strategy:
      matrix:
        include:
          - rust: nightly
            # XXX TODO:
            # doc-tests: true
          - os: macos-latest
            rust: nightly
            # XXX TODO:
            # doc-tests: true
          # TODO: RESOLVE KNOWN BUILD FAILURE ON WINDOWS
          # - os: windows-latest
          #   ...
          # XXX TODO: OTHER RUST NIGHTLY ENTRIES FROM BELOW
    runs-on: ${{ matrix.os }}
    # TODO: IMPROVE CONSISTENCY OF INDENTING WITH INDENTING OF push branches above
    steps:
    - uses: actions/checkout@v4
    - run: rustup default ${{ matrix.rust }}
    # XXX TODO SEPARATE BUILD JOB
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests - all features
      run: cargo test --all-features --verbose
    - name: Run tests - limited feature(s) (alloc only)
      run: cargo test --features alloc --verbose

  doc:
    runs-on: ubuntu-latest
    steps:
    # TODO: IMPROVE CONSISTENCY WITH STEPS ABOVE
    - run: cargo doc --all-features

  # XXX TODO INTEGRATE WITH MATRIX ABOVE
  other:
    runs-on: ubuntu-latest
    # TODO: USE MATRIX FOR TESTING WITH OTHER RUST NIGHTLY VERSIONS
    steps:
    # TEST with MSRV (nightly)
    - run: rustup default nightly-2022-08-24
    - run: cargo test --all-features --all-targets
    # TEST with Rust nightly from mid-2023
    - run: rustup default nightly-2023-07-01
    - run: cargo test --all-features --all-targets
    # TEST with Rust nightly from late-February 2024 to check for correct rustversion conditions
    - run: rustup default nightly-2024-02-17
    - run: cargo test --all-features --all-targets
    - run: rustup default nightly-2024-02-16
    - run: cargo test --all-features --all-targets
    - run: rustup default nightly-2024-02-15
    - run: cargo test --all-features --all-targets
    # TEST with a more recent Rust nightly version (no need for --all-targets)
    - run: rustup default nightly-2024-07-01
    - run: cargo test --all-features
