name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --cfg portable_io_unstable_all

jobs:
  # General TODO items:
  # - try Rust clippy (should avoid all warnings)
  # - check for build & test warnings
  # - enforce consistent Rust fmt (if possible without affecting too much code)
  build:
    strategy:
      matrix:
        include:
          - rust: nightly
          # TODO: RESOLVE KNOWN BUILD FAILURE ON WINDOWS
          # - os: windows-latest
          #   ...
          - os: macos-latest
            rust: nightly
          - rust: nightly-2024-07-01
          - rust: nightly-2023-07-01
            test-options: --all-targets # SKIP doc tests
          - rust: nightly-2022-08-24 # MSRV (nightly)
            test-options: --all-targets # SKIP doc tests
          # TEST with these Rust nightly versions to check for correct rustversion conditions in `src/readbuf.rs`
          - rust: nightly-2024-02-17
            test-options: --all-targets # SKIP doc tests
          - rust: nightly-2024-02-16
            test-options: --all-targets # SKIP doc tests
          - rust: nightly-2024-02-15
            test-options: --all-targets # SKIP doc tests
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    # TODO: IMPROVE CONSISTENCY OF INDENTING WITH INDENTING OF push branches above
    steps:
    - uses: actions/checkout@v4
    - run: rustup default ${{ matrix.rust }}
    # XXX TODO SEPARATE BUILD JOB
    - name: Build
      run: cargo build --all-features ${{ matrix.test-options }} --verbose
    - name: Run tests - all features
      run: cargo test --all-features ${{ matrix.test-options }} --verbose
    - name: Run tests - limited feature(s) (alloc only)
      run: cargo test --features alloc ${{ matrix.test-options }} --verbose

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup default nightly
    - run: cargo doc --all-features
